import type { PlayerSystemSpecs, RecommendedGame } from "@/types"

export const DEFAULT_PLAYER_SPECS: PlayerSystemSpecs = {
  os: "Windows 10",
  cpuTier: 3,
  gpuTier: 3,
  ramGb: 8,
  vramGb: 4,
  storageGb: 40,
}

export const TIER_OPTIONS = [
  { value: 1, label: "Tier 1" },
  { value: 2, label: "Tier 2" },
  { value: 3, label: "Tier 3" },
  { value: 4, label: "Tier 4" },
  { value: 5, label: "Tier 5" },
] as const

export const RECOMMENDED_GAMES: RecommendedGame[] = [
  {
    appId: 730,
    name: "Counter-Strike 2",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg",
    categories: ["FPS", "Competitive"],
    rating: 4.8,
    description: "Free-to-play tactical shooter built for high-skill competitive matches.",
    price: "Free",
  },
  {
    appId: 553850,
    name: "Helldivers 2",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/553850/header.jpg",
    categories: ["Co-op", "Shooter"],
    rating: 4.7,
    description: "Chaotic co-op missions where teamwork and friendly fire share the spotlight.",
    price: "Paid",
  },
  {
    appId: 1172470,
    name: "Apex Legends",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1172470/header.jpg",
    categories: ["Battle Royale", "Hero Shooter"],
    rating: 4.5,
    description: "Fast-paced hero shooter with squad-based battle royale play.",
    price: "Free",
  },
  {
    appId: 252950,
    name: "Rocket League",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/252950/header.jpg",
    categories: ["Sports", "Arcade"],
    rating: 4.8,
    description: "Arcade sports with cars, boost, aerial play, and quick match sessions.",
    price: "Free",
  },
  {
    appId: 1091500,
    name: "Cyberpunk 2077",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg",
    categories: ["RPG", "Open World"],
    rating: 4.6,
    description: "Narrative-driven open-world RPG set in the neon streets of Night City.",
    price: "Paid",
  },
  {
    appId: 271590,
    name: "Grand Theft Auto V",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/271590/header.jpg",
    categories: ["Action", "Open World"],
    rating: 4.9,
    description: "Open-world action sandbox with story mode and endless online chaos.",
    price: "Paid",
  },
  {
    appId: 413150,
    name: "Stardew Valley",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg",
    categories: ["Farming", "Co-op"],
    rating: 4.9,
    description: "Relaxing farming sim with crafting, relationships, and co-op sessions.",
    price: "Paid",
  },
  {
    appId: 322330,
    name: "Don't Starve Together",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/322330/header.jpg",
    categories: ["Survival", "Co-op"],
    rating: 4.6,
    description: "Survival co-op where resource management and madness go hand in hand.",
    price: "Paid",
  },
  {
    appId: 381210,
    name: "Dead by Daylight",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/381210/header.jpg",
    categories: ["Horror", "Multiplayer"],
    rating: 4.4,
    description: "Asymmetric horror multiplayer with tense chases and team escapes.",
    price: "Paid",
  },
  {
    appId: 1174180,
    name: "Red Dead Redemption 2",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg",
    categories: ["Adventure", "Open World"],
    rating: 4.9,
    description: "Slow-burn western adventure with a huge open world and strong story focus.",
    price: "Paid",
  },
  {
    appId: 438100,
    name: "VRChat",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/438100/header.jpg",
    categories: ["Social", "Multiplayer"],
    rating: 4.2,
    description: "Social playground for hanging out, creating worlds, and roleplaying online.",
    price: "Free",
  },
  {
    appId: 578080,
    name: "PUBG: BATTLEGROUNDS",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/578080/header.jpg",
    categories: ["Battle Royale", "Shooter"],
    rating: 4.1,
    description: "Large-scale battle royale with tension, positioning, and survival.",
    price: "Free",
  },
  {
    appId: 440,
    name: "Team Fortress 2",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/440/header.jpg",
    categories: ["FPS", "Team-Based"],
    rating: 4.8,
    description: "Classic team shooter with fast classes, payload maps, and chaotic fun.",
    price: "Free",
  },
  {
    appId: 393380,
    name: "Squad",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/393380/header.jpg",
    categories: ["Tactical", "Co-op"],
    rating: 4.4,
    description: "Tactical infantry combat built around communication and large-scale teamwork.",
    price: "Paid",
  },
  {
    appId: 1196590,
    name: "Resident Evil Village",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1196590/header.jpg",
    categories: ["Horror", "Adventure"],
    rating: 4.7,
    description: "Cinematic horror adventure with exploration, combat, and intense atmosphere.",
    price: "Paid",
  },
  {
    appId: 1245620,
    name: "ELDEN RING",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg",
    categories: ["RPG", "Action"],
    rating: 4.8,
    description: "Expansive action RPG with exploration, build variety, and boss fights.",
    price: "Paid",
  },
  {
    appId: 1551360,
    name: "Forza Horizon 5",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/1551360/header.jpg",
    categories: ["Racing", "Open World"],
    rating: 4.8,
    description: "Open-world racer with huge car variety and festival-style exploration.",
    price: "Paid",
  },
  {
    appId: 739630,
    name: "Phasmophobia",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/739630/header.jpg",
    categories: ["Horror", "Co-op"],
    rating: 4.6,
    description: "Co-op ghost hunting where voice chat and tension matter as much as evidence.",
    price: "Paid",
  },
  {
    appId: 548430,
    name: "Deep Rock Galactic",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/548430/header.jpg",
    categories: ["Co-op", "Shooter"],
    rating: 4.8,
    description: "Mine, shoot, and survive with a squad of space dwarves in procedural caverns.",
    price: "Paid",
  },
]
